architecture:
    random_seed: 1

    neuron_activity:
        goal: 0.1
        smoothness: 3
        two_targets_probability:
            min: 0.2
            max: 0.5
        goal_ceiling: 0.2

    delay:
        min: 4
        max: 8

    root_neuron_delay: 2

    token_delay: 200