architecture:
    random_seed: 1
    neuron_activity:
        goal: 0.1
        calculation_smoothness: 20
        upward_force: 0.5
        downward_force: 0.5
    delay:
        min: 4
        max: 8
    root_neuron_delay: 3
    token_delay: 200
    encoding:
        unit: 128
        scaling_factor: 2