architecture:
    actor_critic:
        stem_fnn: [ 500, 1000, 1000 ]
        lstm:
            input_size: 1000
            hidden_size: 1000
            num_layers: 3
        actor_fnn: [ 1000, 1000, 1000, 750, 500 ]
        critic_fnn: [ 1500, 1500, 1000, 1000, 500, 32, 2 ]
    transformer:
        stem_fnn: [ 1000, 1000, 1000 ]
        qkv_fnn: [ 1000, 1000, 1000, 2000 ]
        attention:
            embed_dim: 2000
            num_heads: 8
        out_fnn: [ 2000, 2000, 10000, 30001 ]