architecture:
    message_agent:
        stem_fnn: [ 100, 100 ]
        lstm:
            input_size: 100
            hidden_size: 200
            num_layers: 3
        head_fnn: [ 200, 200, 150, 100 ]
    routing_agent_fnn: [ 100, 100, 100, 64, 32, 3 ]
    actor:
        stem_fnn: [ 100, 100 ]
        qkv_fnn: [ 100, 100, 100, 100 ]
        attention:
            embed_dim: 100
            num_heads: 8
        out_fnn: [ 800, 800, 600, 400, 200 ]
    critic:
        stem_fnn: [ 100, 100 ]
        qkv_fnn: [ 100, 100, 100, 100 ]
        attention:
            embed_dim: 100
            num_heads: 8
        out_fnn: [ 800, 800, 600, 400, 200 ]