optimization:
    learning_rate: 1e-3
    batch_size:
        regular: 32
        sequence: 16
    training:
        frequency: 0.25
        update_count: 2
    replay_buffer_size: 20000
    polyak_factor:
        initial: 0.1
        final: 5e-4
        decay_rate: 0.997
    loss_weight:
        actor: 1.
        critic: 5.
        routing: 0.25
    loss_emv_factor: 1e-3
    truncation_length: 6