system:
    random_seed: 0
    float_bit_size: 32
    grid_length: 4
    flow:
        max_lifespan: 7
        count: 12
    message_dim: 500
    epsilon:
        initial: 1
        final: 0.25
        decay_rate: 0.999
    gaussian_noise:
        variance:
            initial: 1e-2
            final: 1e-4
            decay_rate: 0.999
        max_abs_z: 5.
    memory_dim: 1000
    discount_rate: 0.95
