system:
    random_seed: 1
    data_size: 32
    grid_length: 6
    vocab_size: 30000
    max_dot_product: 0.4
    flow_lifespan: 7
    flow_count: 12
    message_dim: 500
    epsilon:
        initial: 1
        final: 0.25
        decay_rate: 0.999
    gaussian_noise:
        initial: 1e-2
        final: 1e-4
        decay_rate: 0.999
    memory_dim: 1000
    discount_rate: 0.95
