system:
    random_seed: 0
    grid_length: 4
    flow:
        max_lifespan: 7
        count: 12
    float_bit_size: 32
    dimension:
        message: 64
        memory: 256
    epsilon:
        initial: 1
        final: 0.2
        decay_rate: 0.999
    gaussian_noise:
        var:
            initial: 1e-2
            final: 1e-4
            decay_rate: 0.999
        max_abs_z: 5.
    discount_rate: 0.95