system:
    random_seed: 1
    data_size: 32
    grid_length: 6
    vocab_size: 30000
    max_dot_product: 0.4
    flow_lifespan: 7
    flow_count: 12
    message_dim: 500
    epsilon:
        initial: 1
        final: 0.25
        decay_rate: 0.999
    gaussian_noise:
        initial: 0.02
        final: 0.0001
        decay_rate: 0.999
    reward_clamp: 100
    reward_penalty_factor: 1.5
    memory_dim: 1000
    critic_memory_loss_ratio: 1.25
    discount_rate: 0.9
